# Generated by Django 3.0.6 on 2020-06-10 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200531_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='brief',
            field=models.TextField(max_length=450, null=True),
        ),
    ]
