# Generated by Django 3.0.6 on 2020-06-10 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_brief'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='brief',
            field=models.TextField(max_length=480, null=True),
        ),
    ]
