# Generated by Django 3.0.6 on 2020-07-20 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200610_1331'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookSection',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('BookTitle', models.CharField(max_length=255)),
                ('Author', models.CharField(max_length=100)),
                ('BookDescription', models.TextField(max_length=380, null=True)),
                ('Image', models.ImageField(null=True, upload_to='bookImage/%D/%m/%Y/')),
                ('BookFile', models.FileField(null=True, upload_to='book/%D/%m/%Y/')),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120, null=True, verbose_name='Topic Name')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='topicsub',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Topic'),
        ),
    ]
