# Generated by Django 3.0.6 on 2020-07-20 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20200720_0500'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='rewrite_topicsub',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='rewrite-topicsub same as topicsub exactly'),
        ),
    ]
