# Generated by Django 3.0.6 on 2020-07-20 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20200720_0613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='name',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Topic Name (use underscores and no spaces)'),
        ),
    ]
