# Generated by Django 3.0.6 on 2020-07-20 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20200720_0716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='rewrite_topicsub',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Rewrite Topicsub (same as above) exactly {very compulsory} else this will not appear with "Topic section"'),
        ),
    ]
