# Generated by Django 3.0.6 on 2020-07-21 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20200721_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='monthly',
            field=models.CharField(choices=[('1', 'JAN'), ('2', 'FEB'), ('3', 'MAR'), ('4', 'APR'), ('5', 'MAY'), ('6', 'JUN'), ('7', 'JUL'), ('8', 'AUG'), ('9', 'SEPT'), ('10', 'OCT'), ('11', 'NOV'), ('12', 'DEC')], max_length=20, null=True),
        ),
    ]
