# Generated by Django 3.0.6 on 2020-07-21 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20200721_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='monthly',
            field=models.CharField(choices=[('JAN', 'JAN'), ('FEB', 'FEB'), ('MAR', 'MAR'), ('APR', 'APR'), ('MAY', 'MAY'), ('JUN', 'JUN'), ('JUL', 'JUL'), ('AUG', 'AUG'), ('SEPT', 'SEPT'), ('OCT', 'OCT'), ('NOV', 'NOV'), ('DEC', 'DEC')], max_length=20, null=True),
        ),
    ]
